name = "aeh-frontend"
compatibility_date = "2026-05-24"
compatibility_flags = ["nodejs_compat"]
main = "worker.js"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
binding = "ASSETS"
